<a href="https://colab.research.google.com/github/kapiljoshi014/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#First need to import numpy.
import numpy as np

In [45]:
#This is the basic code to run.
a=np.array([1,2,3,4,5,6])
print(a)



[1 2 3 4 5 6]


In [27]:
# N-dimensional array
d1=np.array([1,2,3,4])
d2=np.array([[1,2,3,4],[5,6,7,8]])
d3=np.array([[[1,2,3,4],[5,6,7,8],[7,8,9,10]]])
d4=np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]]])
print(d1)
print("1D")
print(d2)
print("2D")
print(d3)
print("3D")
print(d4)
print("4D")

[1 2 3 4]
1D
[[1 2 3 4]
 [5 6 7 8]]
2D
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 7  8  9 10]]]
3D
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]]]
4D


In [24]:
## .shape outputs the array's dimensions (rows, cols) to verify data structure before operations.
print(d1.shape)
print(d2.shape)
print(d3.shape)
print(d4.shape)

(4,)
(2, 4)
(1, 3, 4)
(1, 1, 4, 4)


In [51]:
## .reshape() changes array dimensions (e.g., 1D to 2D) without altering data to match required model input shapes.
b=np.array([1,2,3,4,5,6])
b1=b.reshape(2,3)
print(b1)


[[1 2 3]
 [4 5 6]]


In [59]:
#Indexing is the process of accessing individual elements.
c=np.array([10,20,30,40,50])
print(c[0])

#Slicing is a technique used to extract a portion of a sequence.
print(c[0:4])


10
[10 20 30 40]


In [67]:
#Mathematical Operations

d1=np.array([10,20,30,40])
d2=np.array([50,60,70,80])

print(d1+d2)
print(d1*d2)
print(d1.max())
print(d1.sum())

[ 60  80 100 120]
[ 500 1200 2100 3200]
40
100


In [69]:
#Vectorization applies operations to entire arrays simultaneously to replace slow for-loops with fast C-speed execution.
k=np.array([1,2,3,4,5])
new_arr=k*1.1
print(new_arr)


[1.1 2.2 3.3 4.4 5.5]
